spring.application.name=shop-service
server.port=8080
spring.main.web-application-type=reactive

spring.r2dbc.url=r2dbc:h2:mem:///mymarketdb
spring.r2dbc.username=sa
spring.r2dbc.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

spring.redis.host: localhost
spring.redis.port: 6379

#spring.session.store-type=redis
#spring.session.timeout=30m

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

#app.image.dir=C:/temp/images/
app.payment.service.url=http://localhost:8081

spring.r2dbc.properties.logging.level.org.springframework.r2dbc=DEBUG
spring.r2dbc.properties.hibernate.format_sql=true

spring.security.oauth2.client.registration.shop-client.client-id=shop
spring.security.oauth2.client.registration.shop-client.client-secret=shop-secret
spring.security.oauth2.client.registration.shop-client.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.shop-client.scope=payments.read,payments.write
spring.security.oauth2.client.provider.shop-client.token-uri=http://localhost:3000/oauth2/token
spring.security.oauth2.client.provider.shop-client.issuer-uri=http://localhost:3000

logging.level.root=INFO
logging.level.org.springframework=INFO
logging.level.io.r2dbc=DEBUG
logging.level.reactor.netty=DEBUG
logging.level.org.springframework.session=DEBUG
logging.level.org.springframework.session.web.server=DEBUG
#logging.level.org.springframework.session.ReactiveSessionRepository=DEBUG
logging.level.org.springframework.web.server.session=DEBUG
logging.level.org.springframework.web.reactive.result.method.annotation=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.springframework.data.redis=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.web.client.RestTemplate=DEBUG

logging.level.org.springframework.security.oauth2.server.resource=DEBUG
logging.level.org.springframework.security.oauth2.jwt=DEBUG
logging.level.org.springframework.security=DEBUG
Logging.level.org.springframework.security.oauth2.client=DEBUG

logging.level.LoggingOAuth2AccessTokenResponseClient=INFO
logging.level.LoggingOAuth2AuthorizedClientService=INFO
logging.level.OAuth2TokenLoggingFilter=INFO
logging.level.LoggingReactiveOAuth2AuthorizedClientManager=INFO

# ??? ????????? ??????? OAuth2
logging.level.org.springframework.security.web.authentication=DEBUG
logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG

logging.level.ru.yandex.practicum.shop.config=DEBUG
