version: '3.8'

services:
  redis:
    image: redis:7.4.2-bookworm
    container_name: shop-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  authorization-server:
    build:
      context: ./authorization-server
      dockerfile: Dockerfile
    container_name: authorization-server
    ports:
      - "3000:3000"
    environment:
      - AUTHORIZATION-SERVER_ISSUER=http://authorization-server:3000
    restart: unless-stopped

  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    container_name: payment-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK-SET-URI=http://authorization-server:3000/oauth2/jwks
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER-URI=http://authorization-server:3000
    depends_on:
      - redis
      - authorization-server
    restart: unless-stopped

  shop-service:
    build:
      context: ./shop-service
      dockerfile: Dockerfile
    container_name: shop-service
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_REDIS_HOST=redis
      - SPRING_DATA_REDIS_PORT=6379
      - APP_PAYMENT_SERVICE_URL=http://payment-service:8081
#      - APP_PAYMENT_SERVICE_URL=http://localhost:8081
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_SHOP-CLIENT_TOKEN-URI=http://authorization-server:3000/oauth2/token
      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_SHOP-CLIENT_ISSUER-URI=http://authorization-server:3000
#      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_AUTHORIZATION-SERVER_TOKEN-URI=http://authorization-server:3000/oauth2/token
#      - SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_AUTHORIZATION-SERVER_ISSUER-URI=http://authorization-server:3000
    depends_on:
      - redis
      - payment-service
      - authorization-server
    restart: unless-stopped
