spring.application.name=my-market-app

server.port=8080

#spring.datasource.url=jdbc:h2:mem:mymarketdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=password

spring.r2dbc.url=r2dbc:h2:mem:///mymarketdb
spring.r2dbc.username=sa
spring.r2dbc.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

#???? ??? ???????? ???????????
#app.image.dir=C:/temp/images/


logging.level.root=INFO
logging.level.org.springframework=INFO


# ????????? ?????? SQL-????????
spring.r2dbc.properties.logging.level.org.springframework.r2dbc=DEBUG


# ???????????: ?????????? ????????? ????????
logging.level.io.r2dbc=DEBUG
logging.level.reactor.netty=DEBUG


# ??? ?????????????? SQL (??????? ??????)
spring.r2dbc.properties.hibernate.format_sql=true

#
#
## ??? ????
#server.reactive.session.cookie.name=SESSION
#
## ???? ????
#server.reactive.session.cookie.path=/items
#
## HttpOnly (?????? ?? JS)
#server.reactive.session.cookie.http-only=true
#
## Secure (?????? HTTPS)
#server.reactive.session.cookie.secure=false
#
## SameSite (?????? ?? CSRF)
#server.reactive.session.cookie.same-site=Lax
#
## ????? ????? ?????? (? ????????)
#spring.webflux.session.timeout=1800

# ???????? ??????? ??????????? ??? Spring Session
logging.level.org.springframework.session=DEBUG

# ??????????? ??? ?????????? ??????
logging.level.org.springframework.session.web.server=DEBUG
logging.level.org.springframework.session.ReactiveSessionRepository=DEBUG

# ??????????? WebSessionManager ? ????????? ???????????
logging.level.org.springframework.web.server.session=DEBUG

# ?????????????: ??????????? HTTP-?????? (???? ?????)
logging.level.org.springframework.web.reactive.result.method.annotation=DEBUG
logging.level.org.hibernate.SQL=DEBUG

