spring.application.name=payment-service
server.port=8081

spring.r2dbc.url=r2dbc:h2:mem:///paymentService;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=user
spring.r2dbc.password=password

spring.redis.host: localhost
spring.redis.port: 6379
#spring.redis.password: ${REDIS_PASSWORD:}
#spiing.cache.type: redis
#spiing.cache.redis.time-to-live: 120000  # 2
#spiing.cache.redis.cache-null-values: false


spring.jpa.show-sql=true
logging.level.ru.yandex.practicum.payment=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.reactor=DEBUG
logging.level.io.r2dbc.h2=TRACE
logging.level.org.springframework.data.r2dbc=DEBUG
