spring.application.name=payment-service
server.port=8081

spring.r2dbc.url=r2dbc:h2:mem:///paymentService;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.r2dbc.username=user
spring.r2dbc.password=password

spring.redis.host: localhost
spring.redis.port: 6379

spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:3000
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:3000/oauth2/jwks

spring.jpa.show-sql=true
logging.level.ru.yandex.practicum.payment=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.reactor=DEBUG
logging.level.io.r2dbc.h2=TRACE
logging.level.org.springframework.data.r2dbc=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
logging.level.org.springframework.security.oauth2.jwt=DEBUG
logging.level.org.springframework.security.oauth2.server.resource=DEBUG
logging.level.org.springframework.security.oauth2.server.resource.authentication=DEBUG

logging.level.org.springframework.web.reactive.function.client=DEBUG
logging.level.reactor.netty.http.server=DEBUG