spring.application.name=authorization-server
server.port=3000
spring.security.oauth2.authorizationserver.issuer=http://authorization-server:3000


authorization-server.issuer=http://authorization-server:3000

logging.level.org.springframework.security=DEBUG

logging.level.org.springframework.security.oauth2.server.resource=DEBUG
logging.level.org.springframework.security.oauth2.jwt=DEBUG
